### ISSUE TITLE
Failing w/ Dart 2.0.0-dev.16 64-bit ints

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/typed_data#10]
https://travis-ci.org/dart-lang/typed_data/jobs/327932842

**Comment by lrhn** [comment]
See: https://github.com/dart-lang/typed_data/pull/9

**Comment by kevmoo** [comment]
> See: #9

yay!

**Comment by dgrove** [comment]
Can this be closed?

**Comment by kevmoo** [comment]
Closed in https://github.com/dart-lang/typed_data/commit/2d5ef0b252d6473beb8021b3fca0599117a5a0fa
