### ISSUE TITLE
Add ByteData

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/typed_data#3]
I like this package. Is there some reason it doesn't include a ByteData class. I'm building an app that manages medical images and their metadata, which are large but variable size. And I use ByteData for decoding/encoding them.

Jim

**Comment by nex3** [comment]
I'm not sure exactly what you mean by `ByteData`, but there is [a class by that name](https://api.dartlang.org/stable/1.24.2/dart-typed_data/ByteData-class.html) in the `dart:typed_data` core library. Does that meet your needs?

**Comment by jfphilbin** [comment]
No, it doesn't.  As I write into the ByteDataBuffer I'd like it to grow automatically as the other *Buffer classes in your TypedData package in pub does.

 

Does that make sense?

 

I realize this is harder than I originally thought since ByteData does not implement ListBase.

 

Jim

 

Jim Philbin

Co-Chair, DICOM Standards Committee

Principal

Poplar Hill Informatics

jfphilbin@gmail.com

**Comment by nex3** [comment]
The `ByteData` class is just a view that translates between different types of integer lists. If you want to use it as a list, you need to tell it what type of number it's a list *of*—which means choosing a specific buffer class from this package.
